name: ML Pipeline Credit Card Default

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # =========================
    # Set DagsHub Credentials
    # =========================
    - name: Set DagsHub credentials
      run: |
        echo "MLFLOW_TRACKING_URI=https://dagshub.com/Geversonvx/Eksperimen_SML_GilangPutraFirmansyah.mlflow" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_USERNAME=${{ secrets.Geversonvx }}" >> $GITHUB_ENV
        echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.fb5b1af0998d386db67eb8f63631dc0c20a34d72 }}" >> $GITHUB_ENV

    # =========================
    # Run preprocessing
    # =========================
    - name: Run preprocessing
      run: |
        python preprocessing/automate_gilangputrafirmansyah.py

    # =========================
    # Train & register model
    # =========================
    - name: Run model training
      run: |
        python preprocessing/Membangun_model/modelling_final.py
